apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example-after-reboot-check
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: example-after-reboot-check
    spec:
      nodeSelector:
        flatcar-linux-update.v1.flatcar-linux.net/after-reboot: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: example-after-reboot-check
        image: quay.io/stephen_demos/kube-annotate:latest
        command:
        - "/bin/kube-annotate"
        - "flatcar-linux-update.v1.flatcar-linux.net/after-reboot-test"
        - "true"
        env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
