name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run CI checks
        run: make ci

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.45.1
    timeout-minutes: 10
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run lint
        run: make lint check-update-linters

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - uses: actions/checkout@v2
      - name: Codespell test
        uses: codespell-project/actions-codespell@master
        with:
          skip: ./.git,./vendor,./bin,./go.sum
          ignore_words_file: '.codespell.ignorewords'
          check_filenames: true
          check_hidden: true

  image:
    name: Image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test building Docker image
        run: make image

  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install required binaries
        run: GOBIN=/usr/local/bin make install-changelog

      - name: Check changelog format
        run: make test-changelog

  kustomize:
    name: Kustomize
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test rendering manifests using kustomize
        run: make build-kustomize

  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      # Use dedicated action for nice integration with GitHub.
      - uses: returntocorp/semgrep-action@v1
